### ISSUE TITLE
ROS dependency packages fail to be located

### ISSUE THREAD

**Issue by mangusman07** [FleetRobotics/khan_robot#1]
I am on step 1.4 of ROS install http://wiki.ros.org/jade/Installation/Ubuntu

It says if I have issues with dependencies, to runn `sudo apt-get install libgl1-mesa-dev-lts-utopic` but that command also has a chain of dependency issues.

**Comment by jasedit** [comment]
Install ROS Indigo, not ROS Jade. Jade is less stable and will run into issues quite likely.

**Comment by mangusman07** [comment]
I am unable to install `sudo apt-get install ros-indigo-desktop-full` but am able to install `sudo apt-get install ros-indigo-desktop`. I am unsure if this will affect the rest of my installation, but it is being tracked in my notes.

^ this could easily be tied to the fact that many things were preinstalled with asgard

**Comment by jasedit** [comment]
What's the error you get with `ros-indigo-desktop-full`?

**Comment by mangusman07** [comment]
`Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-indigo-desktop-full : Depends: ros-indigo-simulators but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by mangusman07** [comment]
so then I try to install  ros-indigo-simulators but it leads to more broken dependencies

**Comment by jasedit** [comment]
You can often fix that by simply appending the packages not going to install until it finally comes up with a solution - four to six steps in, it'll either say "Ok, but I have to uninstall all this" or "Oh! I can install just fine now."

**Comment by mangusman07** [comment]
i'll try that now, it got to be a pretty deep rabbit hole, but its worth a shot and probably easier than trying to install everything else separately

**Comment by mangusman07** [comment]
These were the dependencies I needed. I am keeping a log of notes and will keep it with my notes

sudo apt-get install ros-indigo-desktop-full ros-indigo-simulators ros-indigo-gazebo-ros-pkgs ros-indigo-gazebo-msgs ros-indigo-gazebo-plugins ros-indigo-gazebo-ros gazebo2 libsdformat1
