### ISSUE TITLE
Choose software license for Khan ROS package

### ISSUE THREAD

**Issue by mangusman07** [FleetRobotics/khan_robot#2]
We need to decide on an open source license type. Typical licenses are BSD, MIT, Boost Software License, GPLv2, GPLv3, LGPLv2.1, LGPLv3

http://opensource.org/licenses/alphabetical

**Comment by jasedit** [comment]
Currently licensed under BSD 3-Clause, as suggested by the ROS [Developer Guide](http://wiki.ros.org/DevelopersGuide).
